### ISSUE TITLE
Refactor & Documentation

### ISSUE THREAD

**Issue by Jade-TheCat** [Jade-TheCat/Humans#2]
# Tasks
- [ ] Neaten code, especially in long files
    - [ ] HumanEntity: Move around functions to be more logical
    - [ ] FlutePartyGui: Move around the widgets to be more logical
- [ ] Add comments to code:
    - [ ] HumanEntity: Functions
    - [ ] HumanEntity: Variables and constants
    - [ ] HumansConfig: Config Values
    - [ ] FlutePartyGui: Widgets
    - [ ] PartyComponent: Functions
    - [ ] FollowBestFriendGoal: Everything
    - [ ] BipedEntityModelMixin: Explain Purpose
    - [ ] EntityRenderDispatcherMixin: Explain Purpose
    - [ ] EntityRenderDispatcherMixin: Functions
    - [ ] MobEntityAccessor: Explain Purpose
    - [ ] SkullBlockEntityAccessor: Explain Purpose (is this used?)
    - [ ] WorldInvoker: Explain Purpose
    - [ ] ZombieEntityMixin: Explain Purpose
    - [ ] HumansServerPlay: Packets

**Comment by theCALiC0** [comment]
Removing from 1.0.0 milestone, will be finished in a later update. This is mostly code readability anyway.
